name: screencasts

channels:
  - conda-forge
  - nodefaults

dependencies:
  - estimagic
  - pip
  - plotly
  - pygraphviz
  - pytask
  - pytask-latex
  - pytask-parallel
  - python-kaleido
  - python=3.10

  - pip:
      - black
      - pre-commit
      - pdbpp
